name: Deploy Distribution Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to S3 and invalidate CloudFront
      env:
        S3_BUCKET_NAME: distribution-cdn.askmiso.com
        CDN_ID: E8PAH2X2YHWM4
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws s3 cp ./ s3://${S3_BUCKET_NAME}/ --acl "public-read" --cache-control no-cache --cache-control max-age=86400 --recursive
        aws cloudfront create-invalidation --distribution-id ${CDN_ID} --paths "/*"
