name: Deploy Distribution Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Set variables
      id: vars
      run: |
        COMMIT_MSG="${{ github.event.commits[0].message }}"
        echo "tar_dir=$(echo $COMMIT_MSG | sed -r 's/^(\[(.+)\])?.*$/\2/')" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
        unzip -q /tmp/awscliv2.zip -d /tmp
        rm /tmp/awscliv2.zip
        sudo /tmp/aws/install --update
        rm -rf /tmp/aws/

    - name: Deploy to S3 and invalidate CloudFront (target directory)
      if: ${{ steps.vars.outputs.tar_dir != '' }}
      env:
        S3_BUCKET_NAME: distribution-cdn.askmiso.com
        CDN_ID: E8PAH2X2YHWM4
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws s3 cp ./${{ steps.vars.outputs.tar_dir}}/ s3://${S3_BUCKET_NAME}/${{ steps.vars.outputs.tar_dir}}/ --cache-control max-age=86400 --exclude ".*/*" --exclude "README.md" --acl "public-read" --recursive
        aws cloudfront create-invalidation --distribution-id ${CDN_ID} --paths "/${{ steps.vars.outputs.tar_dir}}/*"

    - name: Deploy to S3 and invalidate CloudFront (all)
      if: ${{ steps.vars.outputs.tar_dir == '' }}
      env:
        S3_BUCKET_NAME: distribution-cdn.askmiso.com
        CDN_ID: E8PAH2X2YHWM4
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws s3 cp ./ s3://${S3_BUCKET_NAME}/ --cache-control max-age=86400 --exclude ".*/*" --exclude "README.md" --acl "public-read" --recursive
        aws cloudfront create-invalidation --distribution-id ${CDN_ID} --paths "/*"
