name: Test capture target directory from commit message

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: |
        COMMIT_MSG=${{ github.event.push.commits[0].message }}
        echo "tar_dir=$(echo COMMIT_MSG | sed -r 's/^(\[(.+)\])?.*$/\2/')" >> $GITHUB_OUTPUT
    - name: Test step output
      run: |
        echo "${{ steps.vars.outputs.tar_dir }}"
